apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: huggingface-tanzudev-monitor
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: https://tanzuhuggingface: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@huggingface.co/tanzuhuggingface/dev
        ref: origin/main

  template:
    - ytt:
        paths:
          - resources/appcr/pipeline.yaml
          - resources/appcr/values.yaml

  deploy:
    - kapp: {}