apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: huggingface-tanzudev-configmap-monitor
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: https://github.com/agapebondservant/llm-demo.git
        ref: origin/main

  template:
    - ytt:
        paths:
          - resources/appcr/pipeline_configmap.yaml
          - .git/refs/heads/main

  deploy:
    - kapp: {}