#@ load("@ytt:data", "data")
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: llm-huggingface-workflow
spec:
  entrypoint: create-repo
  volumes:
    - name: huggingface-volume
      configMap:
        name: llm-pipeline-configmap
        defaultMode: 0777

  templates:
    - name: create-repo
      inputs:
        parameters:
          - name: mlflow_entry
            value: "promote_model_to_staging"
          - name: mlflow_stage
            value: "Staging"
          - name: git_repo
            value: #@ data.values.git_repo
          - name: experiment_name
            value: #@ data.values.experiment_name
          - name: environment_name
            value: #@ data.values.environment_name
      container:
        image: oawofolu/llm-image-processor
        command: [ python ]
        env:
          - name: DATA_E2E_HUGGINGFACE_TOKEN
            valueFrom:
              secretKeyRef:
                name: huggingface-token
                key: token
        args:
          - ./app/main.py
          - mlflow_entry="{{inputs.parameters.mlflow_entry}}"
          - mlflow_stage="{{inputs.parameters.mlflow_stage}}"
          - git_repo="{{inputs.parameters.git_repo}}"
          - experiment_name="{{inputs.parameters.experiment_name}}"
          - environment_name="{{inputs.parameters.environment_name}}"