---
apiVersion: v1
kind: ConfigMap
metadata:
  name: embeddings-script-volume-configmap
data:
  generate_embeddings.sql: |
    DO $$
    BEGIN
        FOR i in (SELECT coalesce(min(id),0) FROM public.vmware_doc_scrape_metadata where e5_large_token_embedding IS NULL)..
                 (SELECT coalesce(max(id),0) FROM public.vmware_doc_scrape_metadata where e5_large_token_embedding IS NULL) by 10 LOOP
            BEGIN RAISE NOTICE 'updating % to %', i, i + 10; END;

            UPDATE public.vmware_doc_scrape_metadata
            SET e5_large_token_embedding = pgml.embed('intfloat/e5-large', 'passage: ' || token)
            WHERE id BETWEEN i AND i + 10;
            COMMIT;
        END LOOP;
    END;
    $$;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: embeddings
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: psql
          image: postgres:${DATA_E2E_POSTGRESML_VERSION}
          command:
            - psql
            - ${DATA_E2E_LIQUIBASE_TRAINING_DB_URI}
            - --file=/var/lib/postgresql/data/generate_embeddings.sql
          volumeMounts:
            - name: embeddings-script-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: embeddings-script-volume
          configMap:
            name: embeddings-script-volume-configmap
      restartPolicy: Never
  backoffLimit: 4