---
apiVersion: v1
kind: ConfigMap
metadata:
  name: embeddings-script-volume-configmap
data:
  generate_embeddings.sql: |
    DO $$
    BEGIN
        -- updates for vmware_doc_scrape_metadata
        FOR i in (SELECT coalesce(min(id),0) FROM ${XYZSCHEMA}.vmware_doc_scrape_metadata where e5_large_token_embedding IS NULL)..
                 (SELECT coalesce(max(id),0) FROM ${XYZSCHEMA}.vmware_doc_scrape_metadata where e5_large_token_embedding IS NULL) by 100 LOOP
            BEGIN RAISE NOTICE 'updating % to %', i, i + 100; END;

            UPDATE ${XYZSCHEMA}.vmware_doc_scrape_metadata
            SET e5_large_token_embedding = pgml.embed('distilbert-base-uncased', 'passage: ' || token)::vector(768)
            WHERE id BETWEEN i AND i + 100;
            COMMIT;
        END LOOP;

        -- updates for vmware_slack_scrape_metadata
        FOR i in (SELECT coalesce(min(id),0) FROM ${XYZSCHEMA}.vmware_slack_scrape_metadata where e5_large_token_embedding IS NULL)..
                 (SELECT coalesce(max(id),0) FROM ${XYZSCHEMA}.vmware_slack_scrape_metadata where e5_large_token_embedding IS NULL) by 100 LOOP
            BEGIN RAISE NOTICE 'updating % to %', i, i + 100; END;

            UPDATE ${XYZSCHEMA}.vmware_slack_scrape_metadata
            SET e5_large_token_embedding = pgml.embed('distilbert-base-uncased', 'passage: ' || token)::vector(768)
            WHERE id BETWEEN i AND i + 100;
            COMMIT;
        END LOOP;
    END;
    $$;

    CREATE INDEX CONCURRENTLY IF NOT EXISTS index_e5_large_token_embedding
    ON ${XYZSCHEMA}.vmware_doc_scrape_metadata
    USING ivfflat (e5_large_token_embedding vector_cosine_ops)
    WITH (lists = 4);

    CREATE INDEX CONCURRENTLY IF NOT EXISTS index_slack_e5_large_token_embedding
    ON ${XYZSCHEMA}.vmware_slack_scrape_metadata
    USING ivfflat (e5_large_token_embedding vector_cosine_ops)
    WITH (lists = 4);
---
apiVersion: batch/v1
kind: Job
metadata:
  name: embeddings
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: psql
          image: postgres:${DATA_E2E_POSTGRESML_VERSION}
          command:
            - psql
            - ${DATA_E2E_LIQUIBASE_TRAINING_DB_URI}
            - --file=/var/lib/postgresql/data/generate_embeddings.sql
          volumeMounts:
            - name: embeddings-script-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: embeddings-script-volume
          configMap:
            name: embeddings-script-volume-configmap
      restartPolicy: Never
  backoffLimit: 4