global:
  postgresql:
    nameOverride: postgresml
    storageClass: generic
    auth:
      postgresPassword: ${DATA_E2E_BITNAMI_AUTH_POSTGRESPASSWORD}
      username: ${DATA_E2E_BITNAMI_AUTH_USERNAME}
      password: ${DATA_E2E_BITNAMI_AUTH_PASSWORD}
      database: ${DATA_E2E_BITNAMI_AUTH_DATABASE}

image:
  repository: ${DATA_E2E_LLM_REGISTRY_USERNAME}/postgresml-bitnami
  tag: ${DATA_E2E_POSTGRESML_IMAGE_TAG}
  debug: true

primary:
  extendedConfiguration: |
    shared_preload_libraries = 'pgml,vector,pgaudit,pg_stat_statements'

  initdb:
    user: "docker"
    password: "docker"
    scripts:
      00_init_extensions.sh: |-
        #/bin/bash
        echo "Setting huggingface cache directory..."
        mkdir -p /opt/cache/huggingface/transformers
        ls -ltra /opt/cache

  extraEnvVars:
    - name: HF_HOME
      value: ./opt/cache

  service:
    type: LoadBalancer