global:
  postgresql:
    nameOverride: postgresml
    storageClass: generic
    auth:
      postgresPassword: ${DATA_E2E_BITNAMI_AUTH_POSTGRESPASSWORD}
      username: ${DATA_E2E_BITNAMI_AUTH_USERNAME}
      password: ${DATA_E2E_BITNAMI_AUTH_PASSWORD}
      database: ${DATA_E2E_BITNAMI_AUTH_DATABASE}

image:
  repository: ${DATA_E2E_LLM_REGISTRY_USERNAME}/postgresml-bitnami
  tag: ${DATA_E2E_POSTGRESML_IMAGE_TAG}
  debug: true

primary:
  extraVolumes:
    - name: postgres-seed
      persistentVolumeClaim:
        claimName: postgres-seed-pvc
  extendedConfiguration: |
    shared_preload_libraries = 'pgml,vector,pgaudit,pg_stat_statements'

  extraVolumeMounts:
    - mountPath: /docker-entrypoint-initdb.d
      name: postgres-seed

  service:
    type: LoadBalancer