global:
  postgresql:
    nameOverride: postgresml
    storageClass: generic
    auth:
      postgresPassword: ${DATA_E2E_BITNAMI_AUTH_POSTGRESPASSWORD}
      username: ${DATA_E2E_BITNAMI_AUTH_USERNAME}
      password: ${DATA_E2E_BITNAMI_AUTH_PASSWORD}
      database: ${DATA_E2E_BITNAMI_AUTH_DATABASE}

image:
  repository: ${DATA_E2E_LLM_REGISTRY_USERNAME}/postgresml-bitnami
  tag: ${DATA_E2E_POSTGRESML_IMAGE_TAG}
  debug: true
  # pullPolicy: Always

primary:
  extendedConfiguration: |
    shared_preload_libraries = 'pgml,vector,pgaudit,pg_stat_statements'
    tcp_keepalives_idle = 30
    tcp_keepalives_interval = 10
    tcp_keepalives_count = 5

  extraVolumes:
  - name: cache-dir
    persistentVolumeClaim:
      claimName: postgres-seed-pvc

  extraVolumeMounts:
    - mountPath: /opt/cache
      name: cache-dir

  initdb:
    user: "postgres"
    password: "docker"
    scripts:
      00_init_extensions.sh: |-
        #/bin/bash
        echo "Setting huggingface cache directory..."
        ls -ltra /opt/cache

  extraEnvVars:
    - name: HF_HOME
      value: /opt/cache
    - name: TRANSFORMERS_CACHE
      value: /opt/cache/hub
    - name: TORCH_HOME
      value: /opt/cache/torch

  podSecurityContext:
    enabled: true
    fsGroup: 1002

  containerSecurityContext:
    enabled: true
    runAsUser: 1002

  service:
    type: LoadBalancer