---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: llm-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: llm-demo
    apis.apps.tanzu.vmware.com/register-api: "false"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  #image: index.docker.io/oawofolu/image-processor-default@sha256:ba3df083e2abf17117488d918ba2321ec7ba9999981077416725cb3f34b09c6e
  params:
    - name: clusterBuilder
      value: full
  env:
    - name: MLFLOW_TRACKING_URI
      value: http://mlflow.${DATA_E2E_BASE_URL}
    - name: STREAMLIT_SERVER_ENABLE_STATIC_SERVING
      value: true
    - name: DATA_E2E_LLMAPP_TRAINING_DB_URI
      # TODO: Use External Secrets / Vault!
      value: ${DATA_E2E_LLMAPP_TRAINING_DB_URI}
  source:
    git:
      url: https://github.com/agapebondservant/llm-demo.git
      ref:
        branch: main